import { internalMutation } from "./_generated/server";

const DEMO_OFFERS = [
  {
    title: "50% Off Biriyani Festival",
    description: "Enjoy authentic Kacchi Biriyani at half price! Valid for dine-in and takeaway.",
    category: "food",
    discountPercent: 50,
    originalPrice: 500,
    offerPrice: 250,
    latitude: 23.8103,
    longitude: 90.4125,
    address: "Gulshan 2, Dhaka",
    storeName: "Star Kabab",
  },
  {
    title: "30% Off Samsung Galaxy S25",
    description: "Latest Samsung Galaxy S25 at incredible discount. Limited stock available!",
    category: "electronics",
    discountPercent: 30,
    originalPrice: 95000,
    offerPrice: 66500,
    latitude: 23.7806,
    longitude: 90.4074,
    address: "Bashundhara City, Panthapath",
    storeName: "Samsung Store",
  },
  {
    title: "Buy 2 Get 1 Free - Aarong",
    description: "Buy any 2 items and get 1 free on all traditional wear collection.",
    category: "fashion",
    discountPercent: 33,
    latitude: 23.7937,
    longitude: 90.4066,
    address: "Dhanmondi 27, Dhaka",
    storeName: "Aarong",
  },
  {
    title: "60% Off Spa Package",
    description: "Full body massage + facial + hair treatment at 60% off. Book now!",
    category: "beauty",
    discountPercent: 60,
    originalPrice: 5000,
    offerPrice: 2000,
    latitude: 23.7947,
    longitude: 90.4147,
    address: "Banani 11, Dhaka",
    storeName: "Lily Spa & Wellness",
  },
  {
    title: "40% Off Furniture - Hatil",
    description: "Mega furniture sale! Bedroom sets, dining tables and sofas at 40% off.",
    category: "home",
    discountPercent: 40,
    originalPrice: 80000,
    offerPrice: 48000,
    latitude: 23.7515,
    longitude: 90.3923,
    address: "Mirpur Road, Dhanmondi",
    storeName: "Hatil Furniture",
  },
  {
    title: "25% Off Gym Membership",
    description: "Annual gym membership at 25% discount. Includes free trainer sessions.",
    category: "sports",
    discountPercent: 25,
    originalPrice: 24000,
    offerPrice: 18000,
    latitude: 23.8214,
    longitude: 90.4253,
    address: "Gulshan 1, Dhaka",
    storeName: "Gold's Gym Dhaka",
  },
  {
    title: "45% Off Cox's Bazar Package",
    description: "3 nights hotel + flights to Cox's Bazar at 45% off. Couples special!",
    category: "travel",
    discountPercent: 45,
    originalPrice: 25000,
    offerPrice: 13750,
    latitude: 23.7773,
    longitude: 90.3993,
    address: "Green Road, Dhaka",
    storeName: "Tour BD",
  },
  {
    title: "70% Off IELTS Prep Course",
    description: "Complete IELTS preparation course with mock tests. Online + offline.",
    category: "education",
    discountPercent: 70,
    originalPrice: 15000,
    offerPrice: 4500,
    latitude: 23.7364,
    longitude: 90.3923,
    address: "Uttara Sector 7, Dhaka",
    storeName: "British Council Partner",
  },
  {
    title: "Free Health Checkup + 20% Off",
    description: "Free comprehensive health checkup with 20% off all lab tests.",
    category: "healthcare",
    discountPercent: 20,
    latitude: 23.7509,
    longitude: 90.3918,
    address: "Dhanmondi 15, Dhaka",
    storeName: "Popular Diagnostics",
  },
  {
    title: "Buy 1 Get 1 Movie Tickets",
    description: "BOGO on all movie tickets! Valid weekdays only at Star Cineplex.",
    category: "entertainment",
    discountPercent: 50,
    originalPrice: 700,
    offerPrice: 350,
    latitude: 23.8007,
    longitude: 90.4145,
    address: "Bashundhara, Dhaka",
    storeName: "Star Cineplex",
  },
  {
    title: "15% Off Weekly Groceries",
    description: "Get 15% off on all grocery items. Minimum purchase 1000 BDT.",
    category: "groceries",
    discountPercent: 15,
    latitude: 23.7859,
    longitude: 90.4211,
    address: "Mohakhali, Dhaka",
    storeName: "Shwapno",
  },
  {
    title: "35% Off AC Servicing",
    description: "Complete AC cleaning and gas refill at 35% off. Home service available.",
    category: "services",
    discountPercent: 35,
    originalPrice: 3000,
    offerPrice: 1950,
    latitude: 23.8125,
    longitude: 90.4265,
    address: "Badda, Dhaka",
    storeName: "CoolCare BD",
  },
  {
    title: "55% Off Pizza Hut Feast",
    description: "Family feast pizza + sides + drinks at 55% off. Dine-in only.",
    category: "food",
    discountPercent: 55,
    originalPrice: 2200,
    offerPrice: 990,
    latitude: 23.7711,
    longitude: 90.4271,
    address: "Motijheel, Dhaka",
    storeName: "Pizza Hut",
  },
  {
    title: "20% Off iPhone 16 Accessories",
    description: "Original iPhone 16 cases, chargers and accessories at 20% off.",
    category: "electronics",
    discountPercent: 20,
    latitude: 23.7507,
    longitude: 90.3766,
    address: "IDB Bhaban, Agargaon",
    storeName: "iStore BD",
  },
  {
    title: "Buy 3 Get 1 Free - Yellow",
    description: "Select 4 items and pay for only 3! All categories included.",
    category: "fashion",
    discountPercent: 25,
    latitude: 23.7733,
    longitude: 90.4104,
    address: "New Market, Dhaka",
    storeName: "Yellow",
  },
  {
    title: "80% Off Online Courses",
    description: "Web development, data science, and AI courses at 80% off on Bohubrihi.",
    category: "education",
    discountPercent: 80,
    originalPrice: 5000,
    offerPrice: 1000,
    latitude: 23.8059,
    longitude: 90.4167,
    address: "Gulshan, Dhaka",
    storeName: "Bohubrihi",
  },
  {
    title: "40% Off Thai Cuisine",
    description: "Authentic Thai food festival. All mains at 40% off this week!",
    category: "food",
    discountPercent: 40,
    originalPrice: 1500,
    offerPrice: 900,
    latitude: 23.7965,
    longitude: 90.4048,
    address: "Banani DOHS, Dhaka",
    storeName: "Thai Emerald",
  },
  {
    title: "30% Off Dental Cleaning",
    description: "Professional dental cleaning and checkup at 30% off.",
    category: "healthcare",
    discountPercent: 30,
    originalPrice: 3500,
    offerPrice: 2450,
    latitude: 23.7849,
    longitude: 90.3811,
    address: "Mirpur 10, Dhaka",
    storeName: "Dental Care BD",
  },
  {
    title: "Free Delivery + 10% Off",
    description: "Order groceries worth 500+ BDT and get free delivery + 10% off.",
    category: "groceries",
    discountPercent: 10,
    latitude: 23.8248,
    longitude: 90.4192,
    address: "Gulshan 2, Dhaka",
    storeName: "Chaldal",
  },
  {
    title: "65% Off Gaming Mouse & Keyboard",
    description: "Logitech gaming combo at 65% off. Limited time Ramadan special!",
    category: "electronics",
    discountPercent: 65,
    originalPrice: 8000,
    offerPrice: 2800,
    latitude: 23.7555,
    longitude: 90.3908,
    address: "Elephant Road, Dhaka",
    storeName: "Ryans Computer",
  },
  {
    title: "50% Off Kids Amusement Park",
    description: "All rides and attractions at half price on weekends!",
    category: "entertainment",
    discountPercent: 50,
    originalPrice: 1000,
    offerPrice: 500,
    latitude: 23.7563,
    longitude: 90.3751,
    address: "Farmgate, Dhaka",
    storeName: "Fantasy Kingdom",
  },
  {
    title: "25% Off Contact Lenses",
    description: "All branded contact lenses at 25% off. Free eye checkup included.",
    category: "healthcare",
    discountPercent: 25,
    originalPrice: 2000,
    offerPrice: 1500,
    latitude: 23.7893,
    longitude: 90.4178,
    address: "Mohakhali DOHS, Dhaka",
    storeName: "Eye Care Center",
  },
  {
    title: "45% Off Cosmetics - Maybelline",
    description: "Maybelline New York products at 45% off. Foundation, lipstick, mascara.",
    category: "beauty",
    discountPercent: 45,
    originalPrice: 2500,
    offerPrice: 1375,
    latitude: 23.7825,
    longitude: 90.4174,
    address: "Banani, Dhaka",
    storeName: "Maybelline Store",
  },
  {
    title: "35% Off Swimming Classes",
    description: "Monthly swimming classes for beginners and intermediate. Heated pool.",
    category: "sports",
    discountPercent: 35,
    originalPrice: 4000,
    offerPrice: 2600,
    latitude: 23.8157,
    longitude: 90.4234,
    address: "Baridhara, Dhaka",
    storeName: "Aqua Fitness",
  },
  {
    title: "20% Off Sundarban Tour",
    description: "2-day Sundarban eco-tour with boat ride and meals at 20% off.",
    category: "travel",
    discountPercent: 20,
    originalPrice: 8000,
    offerPrice: 6400,
    latitude: 23.7434,
    longitude: 90.4111,
    address: "Sayedabad, Dhaka",
    storeName: "Bengal Tours",
  },
];

export const seedOffers = internalMutation({
  args: {},
  handler: async (ctx) => {
    // Check if offers already exist
    const existing = await ctx.db.query("offers").take(1);
    if (existing.length > 0) {
      return "Database already has offers. Skipping seed.";
    }

    for (const offer of DEMO_OFFERS) {
      await ctx.db.insert("offers", {
        ...offer,
        imageStorageIds: [],
        upvotes: Math.floor(Math.random() * 20) + 5,
        downvotes: Math.floor(Math.random() * 5),
        status: "active",
        createdAt: Date.now() - Math.floor(Math.random() * 7 * 24 * 60 * 60 * 1000),
      });
    }

    return `Seeded ${DEMO_OFFERS.length} demo offers`;
  },
});
